from django.urls import path
from .views import (
    AddAchievementToPlayerView,
    AchievementsUIView,
    AchievementListView,
    ApiRootView,
    CreatePlayerView,
    CreateAccountView,
    LoginView,
    LogoutView,
    MyAchievementsRedirectView,
    PlayerDetailsView,
    RemoveAchievementFromPlayerView,
    WriteStatsView,
    TopRankView,
    FriendsLeaderboardView,
    MyScoreView,
    LeaderboardView,
)

urlpatterns = [
    path("", LoginView.as_view(), name="home"),
    path("my-achievements/", MyAchievementsRedirectView.as_view(), name="my-achievements"),
    path("create-account/", CreateAccountView.as_view(), name="create-account"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("ui/achievements", AchievementsUIView.as_view(), name="achievements-ui"),
    path("api/", ApiRootView.as_view()),
    path("api/achievement/list", AchievementListView.as_view()),
    path("api/achievement/add", AddAchievementToPlayerView.as_view()),
    path("api/achievement/remove", RemoveAchievementFromPlayerView.as_view()),
    path("api/player", PlayerDetailsView.as_view()),
    path("api/player/add", CreatePlayerView.as_view()),
#    path("api/leaderboard/write/", WriteStatsView.as_view()),
#    path("api/leaderboard/top/", TopRankView.as_view()),
#    path("api/leaderboard/friends/", FriendsLeaderboardView.as_view()),
#    path("api/leaderboard/my-score/", MyScoreView.as_view()),
]